#Commented properties are the default values in use, un-comment and specify value to modify
#build:
#  maxIssues: 0
#  excludeCorrectable: false
#  weights:
#  # complexity: 2
#  # LongParameterList: 1
#  # style: 1
#  # comments: 1
#
#config:
#  validation: true
#  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
#  excludes: ''
#
#processors:
#  active: true
#  exclude:
#    - 'DetektProgressListener'
#  # - 'FunctionCountProcessor'
#  # - 'PropertyCountProcessor'
#  # - 'ClassCountProcessor'
#  # - 'PackageCountProcessor'
#  # - 'KtFileCountProcessor'
#
console-reports:
  active: true
#  exclude:
#    - 'ProjectStatisticsReport'
#    - 'ComplexityReport'
#    - 'NotificationReport'
#    #  - 'FindingsReport'
#    - 'FileBasedFindingsReport'
#
comments:
  active: true
  excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
#  AbsentOrWrongFileLicense:
#    active: false
#    licenseTemplateFile: 'license.template'
#  CommentOverPrivateFunction:
#    active: false
#  CommentOverPrivateProperty:
#    active: false
#  EndOfSentenceFormat:
#    active: false
#    endOfSentenceFormat: '([.?!][ \t\n\r\f<])|([.?!:]$)'
#  UndocumentedPublicClass:
#    active: false
#    searchInNestedClass: true
#    searchInInnerClass: true
#    searchInInnerObject: true
#    searchInInnerInterface: true
#  UndocumentedPublicFunction:
#    active: false
#  UndocumentedPublicProperty:
#    active: false

complexity:
  active: true
  LongParameterList:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    ignoreAnnotated: [ 'Module', 'Component', 'Subcomponent', 'BindingAdapter', 'Provides' ]
  LabeledExpression:
    active: false
  ComplexCondition:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  ComplexMethod:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  LargeClass:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.Assert.kt', '**/Assert*.kt', '**/*.Mock.kt', '**/Mock*.kt' ]
  LongMethod:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  NestedBlockDepth:
    threshold: 6
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  TooManyFunctions:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.Assert.kt', '**/Assert*.kt', '**/*.Mock.kt', '**/Mock*.kt' ]

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  RedundantSuspendModifier:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: false
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: false
    methodNames: [ toString, hashCode, equals, finalize ]
  InstanceOfCheckForException:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  NotImplementedDeclaration:
    active: false
  PrintStackTrace:
    active: false
  RethrowCaughtException:
    active: false
  ReturnFromFinally:
    active: false
    ignoreLabeled: false
  SwallowedException:
    active: false
    ignoredExceptionTypes:
      - InterruptedException
      - NumberFormatException
      - ParseException
      - MalformedURLException
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  ThrowingExceptionFromFinally:
    active: false
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false
    exceptions:
      - IllegalArgumentException
      - IllegalStateException
      - IOException
  ThrowingNewInstanceOfSameException:
    active: false
  TooGenericExceptionCaught:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionThrown:
    active: false
    exceptionNames:
      - Error
      - Exception
      - Throwable
      - RuntimeException

formatting:
  active: true
  android: true
  #  autoCorrect: true
  AnnotationOnSeparateLine:
    active: false
  #    autoCorrect: true
  ChainWrapping:
    active: true
  #    autoCorrect: true
  CommentSpacing:
    active: false
  #    autoCorrect: true
  EnumEntryNameCase:
    active: false
  #    autoCorrect: true
  Filename:
    active: true
  FinalNewline:
    active: false
  #    autoCorrect: true
  #    insertFinalNewLine: true
  #  ImportOrdering:
  #    active: false
  #    autoCorrect: true
  #    layout: 'idea'
  #  Indentation:
  #    active: true
  #    autoCorrect: true
  #    indentSize: 4
  #    continuationIndentSize: 8
  MaximumLineLength:
    active: true
    maxLineLength: 140
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  #  ModifierOrdering:
  #    active: true
  #    autoCorrect: true
  MultiLineIfElse:
    active: true
  #    autoCorrect: true
  NoBlankLineBeforeRbrace:
    active: false
  #    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
  #    autoCorrect: true
  NoEmptyClassBody:
    active: true
  #    autoCorrect: true
  #  NoEmptyFirstLineInMethodBlock:
  #    active: false
  #    autoCorrect: true
  NoLineBreakAfterElse:
    active: true
  #    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
  #    autoCorrect: true
  #  NoMultipleSpaces:
  #    active: true
  #    autoCorrect: true
  NoSemicolons:
    active: true
  #    autoCorrect: true
  NoTrailingSpaces:
    active: true
  #    autoCorrect: true
  #  NoUnitReturn:
  #    active: true
  #    autoCorrect: true
  NoUnusedImports:
    active: true
  #    autoCorrect: true
  NoWildcardImports:
    active: true
  PackageName:
    active: true
    autoCorrect: true
  #  ParameterListWrapping:
  #    active: true
  #    autoCorrect: true
  #    indentSize: 4
  SpacingAroundColon:
    active: true
  #    autoCorrect: true
  SpacingAroundComma:
    active: true
  #    autoCorrect: true
  SpacingAroundCurly:
    active: true
  #    autoCorrect: true
  SpacingAroundDot:
    active: true
  #    autoCorrect: true
  SpacingAroundDoubleColon:
    active: false
#    autoCorrect: true
#  SpacingAroundKeyword:
#    active: true
#    autoCorrect: true
#  SpacingAroundOperators:
#    active: true
#    autoCorrect: true
#  SpacingAroundParens:
#    active: true
#    autoCorrect: true
#  SpacingAroundRangeOperator:
#    active: true
#    autoCorrect: true
#  SpacingBetweenDeclarationsWithAnnotations:
#    active: false
#    autoCorrect: true
#  SpacingBetweenDeclarationsWithComments:
#    active: false
#    autoCorrect: true
#  StringTemplate:
#    active: true
#    autoCorrect: true
#
naming:
  #  active: true
  #  ClassNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    classPattern: '[A-Z][a-zA-Z0-9]*'
  #  ConstructorParameterNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    parameterPattern: '[a-z][A-Za-z0-9]*'
  #    privateParameterPattern: '[a-z][A-Za-z0-9]*'
  #    excludeClassPattern: '$^'
  #    ignoreOverridden: true
  #  EnumNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  #  ForbiddenClassName:
  #    active: false
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    forbiddenName: []
  #  FunctionMaxLength:
  #    active: false
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    maximumFunctionNameLength: 30
  #  FunctionMinLength:
  #    active: false
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    minimumFunctionNameLength: 3
  #  FunctionNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    functionPattern: '([a-z][a-zA-Z0-9]*)|(`.*`)'
  #    excludeClassPattern: '$^'
  #    ignoreOverridden: true
  #    ignoreAnnotated: ['Composable']
  #  FunctionParameterNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    parameterPattern: '[a-z][A-Za-z0-9]*'
  #    excludeClassPattern: '$^'
  #    ignoreOverridden: true
  #  InvalidPackageDeclaration:
  #    active: false
  #    rootPackage: ''
  #  MatchingDeclarationName:
  #    active: true
  #    mustBeFirst: true
  MemberNameEqualsClassName:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
  #    active: true
  #    ignoreOverridden: true
  #  ObjectPropertyNaming:
  #    active: true
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
  #    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  #    privatePropertyPattern: '(_)?[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
#  TopLevelPropertyNaming:
#    active: true
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    constantPattern: '[A-Z][_A-Z0-9]*'
#    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
#    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
#  VariableMaxLength:
#    active: false
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    maximumVariableNameLength: 64
#  VariableMinLength:
#    active: false
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    minimumVariableNameLength: 1
#  VariableNaming:
#    active: true
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    variablePattern: '[a-z][A-Za-z0-9]*'
#    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
#    excludeClassPattern: '$^'
#    ignoreOverridden: true
#
performance:
  #  active: true
  ArrayPrimitive:
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]
#    active: true
#  ForEachOnRange:
#    active: true
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#  SpreadOperator:
#    active: true
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#  UnnecessaryTemporaryInstantiation:
#    active: true
#
#potential-bugs:
#  active: true
#  Deprecation:
#    active: false
#  DuplicateCaseInWhenExpression:
#    active: true
#  EqualsAlwaysReturnsTrueOrFalse:
#    active: true
#  EqualsWithHashCodeExist:
#    active: true
#  ExplicitGarbageCollectionCall:
#    active: true
#  HasPlatformType:
#    active: false
#  IgnoredReturnValue:
#    active: false
#    restrictToAnnotatedMethods: true
#    returnValueAnnotations: ['*.CheckReturnValue', '*.CheckResult']
#  ImplicitDefaultLocale:
#    active: false
#  InvalidRange:
#    active: true
#  IteratorHasNextCallsNextMethod:
#    active: true
#  IteratorNotThrowingNoSuchElementException:
#    active: true
#  LateinitUsage:
#    active: false
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    excludeAnnotatedProperties: []
#    ignoreOnClassesPattern: ''
#  MapGetWithNotNullAssertionOperator:
#    active: false
#  MissingWhenCase:
#    active: true
#  RedundantElseInWhen:
#    active: true
#  UnconditionalJumpStatementInLoop:
#    active: false
#  UnnecessaryNotNullOperator:
#    active: false
#  UnnecessarySafeCall:
#    active: false
#  UnreachableCode:
#    active: true
#  UnsafeCallOnNullableType:
#    active: true
#  UnsafeCast:
#    active: false
#  UselessPostfixExpression:
#    active: false
#  WrongEqualsTypeParameter:
#    active: true
#
style:
  #  active: true
  #  CollapsibleIfStatements:
  #    active: false
  #  DataClassContainsFunctions:
  #    active: false
  #    conversionFunctionPrefix: 'to'
  #  DataClassShouldBeImmutable:
  #    active: false
  #  EqualsNullCall:
  #    active: true
  #  EqualsOnSignatureLine:
  #    active: false
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  #  ExpressionBodySyntax:
  #    active: true
  #    includeLineWrapping: false
  ForbiddenComment:
    active: false
  #    values: ['TODO:', 'FIXME:', 'STOPSHIP:']
  #    allowedPatterns: ''
  #  ForbiddenImport:
  #    active: false
  #    imports: []
  #    forbiddenPatterns: ''
  #  ForbiddenMethodCall:
  #    active: false
  #    methods: ['kotlin.io.println', 'kotlin.io.print']
  #  ForbiddenPublicDataClass:
  #    active: false
  #    ignorePackages: ['*.internal', '*.internal.*']
  #  ForbiddenVoid:
  #    active: false
  #    ignoreOverridden: false
  #    ignoreUsageInGenerics: false
  #  FunctionOnlyReturningConstant:
  #    active: true
  #    ignoreOverridableFunction: true
  #    excludedFunctions: 'describeContents'
  #    excludeAnnotatedFunction: ['dagger.Provides']
  #  LibraryCodeMustSpecifyReturnType:
  #    active: true
  #  LoopWithTooManyJumpStatements:
  #    active: true
  #    maxJumpCount: 1
  MagicNumber:
    active: false
  #    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**', '**/buildSrc/**']
  #    ignoreNumbers: ['-1', '0', '1', '2']
  #    ignoreHashCodeFunction: true
  #    ignorePropertyDeclaration: false
  #    ignoreLocalVariableDeclaration: false
  #    ignoreConstantDeclaration: true
  #    ignoreCompanionObjectPropertyDeclaration: true
  #    ignoreAnnotation: false
  #    ignoreNamedArgument: true
  #    ignoreEnums: false
  #    ignoreRanges: false
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  MaxLineLength:
    #    active: true
    maxLineLength: 140
    #    excludePackageStatements: true
    #    excludeImportStatements: true
    excludeCommentStatements: true
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

  #  MayBeConst:
  #    active: true
  #  ModifierOrder:
  #    active: true
  #  NestedClassesVisibility:
  #    active: false
  NewLineAtEndOfFile:
    active: false
  NoTabs:
    active: true
  #  OptionalAbstractKeyword:
  #    active: true
  OptionalUnit:
    active: true
  #  OptionalWhenBraces:
  #    active: true
  #  PreferToOverPairSyntax:
  #    active: false
  #  ProtectedMemberInFinalClass:
  #    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  ReturnCount:
    active: false
  #    max: 2
  #    excludedFunctions: 'equals'
  #    excludeLabeled: false
  #    excludeReturnFromLambda: true
  #    excludeGuardClauses: false
  #  SafeCast:
  #    active: true
  #  SerialVersionUIDInSerializableClass:
  #    active: false
  SpacingBetweenPackageAndImports:
    active: true
  #  ThrowsCount:
  #    active: true
  #    max: 2
  TrailingWhitespace:
    active: false
  #  UnderscoresInNumericLiterals:
  #    active: false
  #    acceptableDecimalLength: 5
  UnnecessaryAbstractClass:
    active: false
  #    excludeAnnotatedClasses: ['dagger.Module']
  #  UnnecessaryAnnotationUseSiteTarget:
  #    active: false
  UnnecessaryApply:
    active: true
  #  UnnecessaryInheritance:
  #    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  #  UntilInsteadOfRangeTo:
  #    active: false
  UnusedImports:
    active: true
  #  UnusedPrivateClass:
  #    active: true
  UnusedPrivateMember:
    active: true
    #    allowedNames: '(_|ignored|expected|serialVersionUID)'
    #  UseArrayLiteralsInAnnotations:
    #    active: false
    #  UseCheckOrError:
    #    active: false
  UseDataClass:
    active: true
  #    excludeAnnotatedClasses: []
  #    allowVars: false
  UseIfInsteadOfWhen:
    active: false
  #  UseRequire:
  #    active: false
  #  UselessCallOnNotNull:
  #    active: true
  #  UtilityClassWithPublicConstructor:
  #    active: true
  VarCouldBeVal:
    active: true
#  WildcardImport:
#    active: true
#    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
#    excludeImports: ['java.util.*', 'kotlinx.android.synthetic.*']