name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  assmeble:

    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build app package
        run: ./gradlew assemble

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Debug build
        run: ./gradlew test

      - name: Extract JacocoReport
        run: ./gradlew jacocoReport

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

  verify:

    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Detekt
        run: ./gradlew detekt

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
